var testSeparators = require('./_utils').testSeparators

module.exports = function (t) {
  t.test('*', function (t) {
    t.test(
      'Matches 0 or more non-separator characters',
      testSeparators(function (t, m, sep) {
        t.ok(m('*')(''))
        t.ok(m('*')('o'))
        t.ok(m('*')('one'))
        t.ok(m('one*')('one'))
        t.ok(m('one*')('onet'))
        t.ok(m('one*')('onetwo'))
        t.ok(m('one*')('one_two'))
        t.notOk(m('one*')('on'))
        t.notOk(m('one*')('ont'))
        t.notOk(m('one*')('onte'))

        t.ok(m('*/*')('one/'))
        t.ok(m('*/*')('one/t'))
        t.ok(m('*/*')('one/two'))
        t.ok(m('*/*/*')('one/two/three'))
        t.ok(m('*/*/*')('//'))
        t.ok(m('one/*')('one/two'))
        t.ok(m('one/*')('one/*'))
        t.ok(m('one/*')('one/**'))
        t.ok(m('one/*')('one/***'))
        t.ok(m('one/*')('one/'))
        t.ok(m('one/*')('one/t'))
        t.ok(m('one/*/three')('one/two/three'))
        t.ok(m('one/*/three/')('one/two/three/'))
        t.ok(m('one/*/three/*')('one/two/three/'))
        t.ok(m('one/*/three/*')('one/two/three/four'))
        t.ok(m('*two')('two'))
        t.ok(m('*two')('onetwo'))
        t.ok(m('one*three')('onetwothree'))
        t.ok(m('one*three')('onethree'))
        t.ok(m('one/*three')('one/twothree'))
        t.ok(m('one/two*')('one/twothree'))
        t.ok(m('*/')('/'))
        t.ok(m('*/one')('/one'))
        t.ok(m('*n*')('one'))
        t.ok(m('*n*')('oonee'))
        t.ok(m('*n*')('n'))
        t.ok(m('o*n*e')('one'))
        t.ok(m('o*n*e')('oone'))
        t.ok(m('o*n*e')('onne'))
        t.ok(m('o*n*e')('oonne'))
        t.ok(m('*ne/*o')('ne/o'))
        t.ok(m('*ne/*o')('one/o'))
        t.ok(m('*ne/*o')('ne/two'))
        t.ok(m('*ne/*o')('one/two'))
        t.ok(m('*/*o')('/o'))
        t.ok(m('*/*o')('/two'))
        t.ok(m('*/*o')('one/two'))
        t.notOk(m('one/*')(''))
        t.notOk(m('one/*')('/'))
        t.notOk(m('one/*')('//'))
        t.notOk(m('one/*')('two/three'))
        t.notOk(m('*/one')(''))
        t.notOk(m('*/one')('/'))
        t.notOk(m('*/one')('//'))
        t.notOk(m('*/one')('one/two/three'))
        t.notOk(m('*/one')('one/two'))
        t.notOk(m('*n*')(''))
        t.notOk(m('*n*')('/'))
        t.notOk(m('o*n*e')(' one '))

        if (sep) {
          t.notOk(m('*')('/'))
          t.notOk(m('*')('//'))
          t.notOk(m('*')('one/two'))
          t.notOk(m('*')('one/'))
          t.notOk(m('*')('/one'))
          t.notOk(m('one/*')('one/two/three'))
          t.notOk(m('one/*')('one'))
          t.notOk(m('one/*')('/one'))
          t.notOk(m('*/one')('one'))
          t.notOk(m('*/one')('one/'))
          t.notOk(m('*two')('one/two'))
          t.notOk(m('*n*')('n/'))
          t.notOk(m('*n*')('one/'))
          t.notOk(m('*n*')('/n'))
          t.notOk(m('*n*')('/n/'))
          t.notOk(m('o*n*e')('/one'))
          t.notOk(m('o*n*e')('one/'))
          t.notOk(m('o*n*e')('o/ne'))
          t.notOk(m('o*n*e')('on/e'))
          t.notOk(m('o*n*e')('o/n/e'))
          t.notOk(m('*ne/*o')('/ne/o'))
          t.notOk(m('*/*o')('//o'))
          t.notOk(m('*/*o')('/o/'))
        }
      })
    )

    t.test(
      'When escaped, treated literally',
      testSeparators(function (t, m) {
        // TODO: add cases with separators

        t.ok(m('\\*')('*'))
        t.notOk(m('\\*')(''))
        t.notOk(m('\\*')('\\*'))
        t.notOk(m('\\*')('o\\*'))
        t.notOk(m('\\*')('\\*e'))
        t.notOk(m('\\*')('\\**'))
        t.notOk(m('\\*')('o'))
        t.notOk(m('\\*')('one'))
        t.notOk(m('\\*')('\\o'))
        t.notOk(m('\\*')('\\'))

        t.ok(m('one\\*')('one*'))
        t.notOk(m('one\\*')(''))
        t.notOk(m('one\\*')('one'))
        t.notOk(m('one\\*')('one\\'))
        t.notOk(m('one\\*')('one\\*'))
        t.notOk(m('one\\*')('one*t'))
        t.notOk(m('one\\*')('one\\*two'))
        t.notOk(m('one\\*')('one\\**'))
        t.notOk(m('one\\*')('\\*'))
        t.notOk(m('one\\*')('*\\*'))
        t.notOk(m('one\\*')('\\'))

        t.ok(m('\\*one')('*one'))
        t.notOk(m('\\*one')(''))
        t.notOk(m('\\*one')('one'))
        t.notOk(m('\\*one')('\\one'))
        t.notOk(m('\\*one')('\\*one'))
        t.notOk(m('\\*one')('t*one'))
        t.notOk(m('\\*one')('two\\*one'))
        t.notOk(m('\\*one')('\\*'))
        t.notOk(m('\\*one')('\\**'))
        t.notOk(m('\\*one')('\\'))

        t.ok(m('o\\*e')('o*e'))
        t.notOk(m('o\\*e')(''))
        t.notOk(m('o\\*e')('one'))
        t.notOk(m('o\\*e')('o\\e'))
        t.notOk(m('o\\*e')('o\\*e'))
        t.notOk(m('o\\*e')('o*te'))
        t.notOk(m('o\\*e')('\\*'))
        t.notOk(m('o\\*e')('\\**'))
        t.notOk(m('o\\*e')('\\'))
      })
    )
  })
}
