var suite = require('./_utils').suite

module.exports = suite(function (t) {
  t.test('? - single-char wildcard', function (t) {
    t.testPerSeparator('Matches one non-separator character', function (t, sep) {
      t.match('?')('o')
      t.match('?')('t')
      t.match('??')('on')
      t.match('??')('ot')
      t.match('???')('one')
      t.match('o?e')('one')
      t.match('?ne')('one')
      t.match('?ne')('ane')
      t.match('on?')('one')
      t.match('on?')('ont')
      t.match('o??')('one')
      t.match('o??')('ota')
      t.match('?n?')('one')
      t.match('/?')('/o')
      t.match('/??')('/on')
      t.match('?/')('o/')
      t.match('??/')('on/')
      t.match('?/?')('o/e')
      t.match('one/?')('one/t')
      t.match('one/t?o')('one/two')
      t.match('one/tw?')('one/two')
      t.match('o?e/tw?')('one/two')
      t.dontMatch('?')('')
      t.dontMatch('?')('//')
      t.dontMatch('?')('on')
      t.dontMatch('?')('o/n')
      t.dontMatch('??')('')
      t.dontMatch('??')('/')
      t.dontMatch('??')('o')
      t.dontMatch('??')('on/e')
      t.dontMatch('??')('one')
      t.dontMatch('???')('on')
      t.dontMatch('???')('one/two')
      t.dontMatch('???')('/')
      t.dontMatch('???')('//')
      t.dontMatch('o?e')('oe')
      t.dontMatch('?ne')('ne')
      t.dontMatch('on?')('on')
      t.dontMatch('?one')('one')
      t.dontMatch('o??')('o')
      t.dontMatch('?/')('')
      t.dontMatch('?/')('/')
      t.dontMatch('?/')('///')
      t.dontMatch('?/')('on')
      t.dontMatch('?/')('on/')
      t.dontMatch('?/')('one')
      t.dontMatch('?/')('one/')
      t.dontMatch('/?')('')
      t.dontMatch('/?')('/')
      t.dontMatch('/?')('///')
      t.dontMatch('/?')('on')
      t.dontMatch('/?')('/on')
      t.dontMatch('/?')('one')
      t.dontMatch('/?')('/one')
      t.dontMatch('??/?')('on')
      t.dontMatch('one/t?o')('one/to')
      t.dontMatch('?/?')('on')
      t.dontMatch('?')('/o')
      t.dontMatch('o??')('on/e')
      t.dontMatch('?/')('o')
      t.dontMatch('/?')('o')
      t.dontMatch('/??')('on')
      t.dontMatch('o?e/tw?')('onetwo')

      if (sep) {
        t.dontMatch('?')('/')
        t.dontMatch('??')('//')
        t.dontMatch('???')('/on')
        t.dontMatch('???')('///')
        t.dontMatch('on?')('on/')
        t.dontMatch('?one')('/one')
        t.dontMatch('o??')('o/e')
        t.dontMatch('o??')('o//')
        t.dontMatch('o???')('on/e')
        t.dontMatch('one?two')('one/two')
        t.dontMatch('?/')('//')
        t.dontMatch('?/?')('///')
        t.dontMatch('/?')('//')
        t.dontMatch('/??')('///')
        t.dontMatch('one/tw?')('one/tw/')
      }
    })

    t.testPerSeparator('When escaped, treated literally', function (t) {
      // TODO: add cases with separators, multiple backslashes

      t.match('\\?')('?')
      t.match('one\\?')('one?')
      t.match('\\?one')('?one')
      t.match('o\\?e')('o?e')

      t.dontMatch('\\?')('')
      t.dontMatch('\\?')('o')
      t.dontMatch('\\?')('\\?')
      t.dontMatch('\\?')('\\o')
      t.dontMatch('\\?')('\\')

      t.dontMatch('one\\?')('')
      t.dontMatch('one\\?')('onet')
      t.dontMatch('one\\?')('\\?')
      t.dontMatch('one\\?')('????')
      t.dontMatch('one\\?')('one\\')
      t.dontMatch('one\\?')('one\\t')
      t.dontMatch('one\\?')('one\\?')

      t.dontMatch('\\?one')('')
      t.dontMatch('\\?one')('tone')
      t.dontMatch('\\?one')('????')
      t.dontMatch('\\?one')('\\?')
      t.dontMatch('\\?one')('\\one')
      t.dontMatch('\\?one')('\\tone')
      t.dontMatch('\\?one')('\\?one')

      t.dontMatch('o\\?e')('')
      t.dontMatch('o\\?e')('o\\?e')
      t.dontMatch('o\\?e')('o\\ne')
      t.dontMatch('o\\?e')('o\\e')
      t.dontMatch('o\\?e')('\\?')
      t.dontMatch('o\\?e')('oo?e')
      t.dontMatch('o\\?e')('o??e')
      t.dontMatch('o\\?e')('??e')
      t.dontMatch('o\\?e')('???')
    })

    t.testPerSeparator('Can be mixed escaped and unescaped', function (t) {
      // TODO: add cases with separators, multiple backslashes

      t.match('\\?_?')('?_o')
      t.match('\\?_?')('?_n')
      t.match('?_\\?')('o_?')
      t.match('?_\\?')('n_?')
      t.match('\\??e')('?ne')
      t.match('?\\?e')('n?e')
      t.match('?\\??')('o?e')
      t.match('o?e_t\\?o_?hree')('one_t?o_three')

      t.dontMatch('\\??')('')
      t.dontMatch('?\\?')('')
      t.dontMatch('\\??')('on')
      t.dontMatch('\\??')('\\n')
    })
  })
})
