var testSeparators = require('./_utils').testSeparators

module.exports = function (t) {
  t.test('?', function (t) {
    t.test(
      'Matches one non-separator character',
      testSeparators(function (t, m, sep) {
        t.ok(m('?')('o'))
        t.ok(m('?')('t'))
        t.ok(m('??')('on'))
        t.ok(m('??')('ot'))
        t.ok(m('???')('one'))
        t.ok(m('o?e')('one'))
        t.ok(m('?ne')('one'))
        t.ok(m('?ne')('ane'))
        t.ok(m('on?')('one'))
        t.ok(m('on?')('ont'))
        t.ok(m('o??')('one'))
        t.ok(m('o??')('ota'))
        t.ok(m('?n?')('one'))
        t.ok(m('/?')('/o'))
        t.ok(m('/??')('/on'))
        t.ok(m('?/')('o/'))
        t.ok(m('??/')('on/'))
        t.ok(m('?/?')('o/e'))
        t.ok(m('one/?')('one/t'))
        t.ok(m('one/t?o')('one/two'))
        t.ok(m('one/tw?')('one/two'))
        t.ok(m('o?e/tw?')('one/two'))
        t.notOk(m('?')(''))
        t.notOk(m('?')('/'))
        t.notOk(m('?')('//'))
        t.notOk(m('?')('on'))
        t.notOk(m('?')('o/n'))
        t.notOk(m('??')(''))
        t.notOk(m('??')('/'))
        t.notOk(m('??')('//'))
        t.notOk(m('??')('o'))
        t.notOk(m('??')('on/e'))
        t.notOk(m('??')('one'))
        t.notOk(m('???')('on'))
        t.notOk(m('???')('/on'))
        t.notOk(m('???')('one/two'))
        t.notOk(m('???')('/'))
        t.notOk(m('???')('//'))
        t.notOk(m('???')('///'))
        t.notOk(m('o?e')('oe'))
        t.notOk(m('?ne')('ne'))
        t.notOk(m('on?')('on'))
        t.notOk(m('on?')('on/'))
        t.notOk(m('?one')('one'))
        t.notOk(m('?one')('/one'))
        t.notOk(m('o??')('o//'))
        t.notOk(m('o??')('o/e'))
        t.notOk(m('o??')('o'))
        t.notOk(m('o???')('on/e'))
        t.notOk(m('one?two')('one/two'))
        t.notOk(m('?/')(''))
        t.notOk(m('?/')('/'))
        t.notOk(m('?/')('//'))
        t.notOk(m('?/')('///'))
        t.notOk(m('?/')('on'))
        t.notOk(m('?/')('on/'))
        t.notOk(m('?/')('one'))
        t.notOk(m('?/')('one/'))
        t.notOk(m('?/?')('///'))
        t.notOk(m('/?')(''))
        t.notOk(m('/?')('/'))
        t.notOk(m('/?')('//'))
        t.notOk(m('/?')('///'))
        t.notOk(m('/?')('on'))
        t.notOk(m('/?')('/on'))
        t.notOk(m('/?')('one'))
        t.notOk(m('/?')('/one'))
        t.notOk(m('/?' + '?')('///'))
        t.notOk(m('??/?')('on'))
        t.notOk(m('one/t?o')('one/to'))
        t.notOk(m('one/tw?')('one/tw/'))

        if (sep) {
          t.notOk(m('?/?')('on'))
          t.notOk(m('?')('/o'))
          t.notOk(m('o??')('on/e'))
          t.notOk(m('?/')('o'))
          t.notOk(m('/?')('o'))
          t.notOk(m('/?' + '?')('on'))
          t.notOk(m('o?e/tw?')('onetwo'))
        }
      })
    )

    t.test(
      'When escaped, treated literally',
      testSeparators(function (t, m) {
        // TODO: add cases with separators, multiple backslashes

        t.ok(m('\\?')('?'))
        t.ok(m('one\\?')('one?'))
        t.ok(m('\\?one')('?one'))
        t.ok(m('o\\?e')('o?e'))
        t.ok(m('o\\?e')('o?e'))

        t.notOk(m('\\?')(''))
        t.notOk(m('\\?')('o'))
        t.notOk(m('\\?')('\\?'))
        t.notOk(m('\\?')('\\o'))
        t.notOk(m('\\?')('\\'))

        t.notOk(m('one\\?')(''))
        t.notOk(m('one\\?')('onet'))
        t.notOk(m('one\\?')('\\?'))
        t.notOk(m('one\\?')('????'))
        t.notOk(m('one\\?')('one\\'))
        t.notOk(m('one\\?')('one\\t'))
        t.notOk(m('one\\?')('one\\?'))

        t.notOk(m('\\?one')(''))
        t.notOk(m('\\?one')('tone'))
        t.notOk(m('\\?one')('????'))
        t.notOk(m('\\?one')('\\?'))
        t.notOk(m('\\?one')('\\one'))
        t.notOk(m('\\?one')('\\tone'))
        t.notOk(m('\\?one')('\\?one'))

        t.notOk(m('o\\?e')(''))
        t.notOk(m('o\\?e')('o\\?e'))
        t.notOk(m('o\\?e')('o\\ne'))
        t.notOk(m('o\\?e')('o\\e'))
        t.notOk(m('o\\?e')('\\?'))
        t.notOk(m('o\\?e')('oo?e'))
        t.notOk(m('o\\?e')('o??e'))
        t.notOk(m('o\\?e')('??e'))
        t.notOk(m('o\\?e')('???'))
      })
    )

    t.test(
      'Can be mixed escaped and unescaped',
      testSeparators(function (t, m) {
        // TODO: add cases with separators, multiple backslashes

        t.ok(m('\\?_?')('?_o'))
        t.ok(m('\\?_?')('?_n'))
        t.ok(m('?_\\?')('o_?'))
        t.ok(m('?_\\?')('n_?'))
        t.ok(m('\\??e')('?ne'))
        t.ok(m('?\\?e')('n?e'))
        t.ok(m('?\\??')('o?e'))
        t.ok(m('o?e_t\\?o_?hree')('one_t?o_three'))

        t.notOk(m('\\??')(''))
        t.notOk(m('?\\?')(''))
        t.notOk(m('\\??')('on'))
        t.notOk(m('\\??')('\\n'))
      })
    )
  })
}
