name: Publish to GPR

on:
  workflow_dispatch:
  push:
    tags: 'v*.*.*'

jobs:
  publish:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Wait for the CI workflow to complete
        id: wait-for-ci
        uses: fountainhead/action-wait-for-check@v1.0.0
        with:
          checkName: ci (${{ matrix.os }}, ${{ matrix.node }})
          token: ${{ secrets.GITHUB_TOKEN }}
      - if: steps.wait-for-ci.outputs.conclusion == 'failure'
        run: exit 1
      - name: Check out the repository
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
          registry-url: https://npm.pkg.github.com
      - name: Add the repository owner as the scope to the package name
        run: 'node -e "var p = require(''./package.json''); p.name = p.name[0] === ''@'' ? p.name : ''@${{ github.repository_owner }}/'' + p.name; require(''fs'').writeFileSync(''./package.json'', JSON.stringify(p))"'
      - name: Install the dependencies using the package manager whose lock file is in the root dir
        uses: jaid/action-npm-install@v1.2.1
      - name: Publish the package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
