name: Publish to GPR

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for the CI workflow to complete
        uses: lewagon/wait-on-check-action@v0.1-beta.2
        with:
          check-name: ci
          ref: master
          wait-interval: 10
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Check out the repository
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: https://npm.pkg.github.com
      - name: Add the repository owner as the scope to the package name
        run: sed -i -r 's/("name":\s*")/\1@${{ github.repository_owner }}\//' package.json
      - name: Install the dependencies using the package manager whose lock file is in the root dir
        uses: jaid/action-npm-install@v1.2.1
      - name: Publish the package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
